#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m -1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule --add "Emacs" state=tiled

SCRIPTS="$HOME/.config/bspwm/bspwm.d"

for f in "$SCRIPTS"/*.sh; do
    [ -e "$f" ] || continue

    # shellcheck source=/dev/null
    . "$f"
done
