#! /bin/sh

xrdb ~/.Xresources

pgrep -x sxhkd > /dev/null || sxhkd -m -1 &

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


SCRIPTS="$HOME/.config/bspwm/bspwm.d"

for f in "$SCRIPTS"/*.sh; do
    # shellcheck source=/dev/null
    . "$f"
done

pgrep -x dunst >/dev/null || dunst &
pgrep nextcloud >/dev/null || nextcloud --background &

kitty &
